server:
  port: 3434

spring:
  datasource:
    url: jdbc:postgresql://db-pfpd-yoda-postgresql.postgres.database.azure.com:5432/postgres
    username: secret
    password: secret

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always